management:
  metrics:
    export:
      datadog:
        api-key: 6371a91f4812320fdb6bf3441e6fb7df
        application-key: 5a5aa56e2b554e1d3767fd4d3ba18d94faed49bb
        host-tag: ${spring.application.name}.domain.tld
        step: 10s
        enaboed: true